<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="col-xs-12">
    <div class="col-xs-12 copyright-footer">
        Copyright © 2016 , all rights are reserved.
        <br/>
        Designed & Developed By MakeUsAWebsite
        <div class="footer-t-shirts-background">
            <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/footer-background-tshirts.png') ?>" alt="<?php echo __('footer background') ?>"/>
        </div>
    </div>
    <div class="col-xs-12 payment-footer">
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/footer-ssl.png') ?>" alt="<?php echo __('ssl') ?>"/>
        <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/footer-payments.png') ?>" alt="<?php echo __('payments') ?>"/>
        <a href="https://www.braintreegateway.com/merchants/YOUR_MERCHANT_ID/verified" target="_blank">
            <img src="https://s3.amazonaws.com/braintree-badges/braintree-badge-wide-light.png" width="280px" height="44px" border="0"/>
        </a>
    </div>
</div>