<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<div class="col-sm-9 col-xs-9 account-area-container">
    <form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
        <fieldset class="fieldset info">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="block-title"><span><?php /* @escapeNotVerified */ echo __('Account Information') ?></span></div><br>
            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>
            <div class="col-xs-12 col-sm-6 field email required">
                <input type="email" name="email" id="email" placeholder="Email *" value="<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?php echo $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?php echo $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?php echo $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
            <div class="col-xs-12 col-sm-6">
                <input type="checkbox" name="change_password" id="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox"/>
                <label class="label" for="change-password"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></label>
            </div>
        </fieldset>
        <fieldset class="fieldset password">
            <div class="col-xs-12 col-sm-6">
                <div class="block-title"><span><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></div><br>
                <div class="account-area-field field password current required">
                    <input placeholder="Current Password *" type="password" class="input-text" name="current_password" id="current-password" autocomplete="off">
                </div>
                <div class="account-area-field field new password required">
                    <input placeholder="New Password *" type="password" class="input-text" name="password" id="password" autocomplete="off">
                </div>
                <div class="account-area-field field confirm password required">
                    <input placeholder="<?php /* @escapeNotVerified */ echo __('Confirm New Password') ?>" type="password" class="input-text" name="password_confirmation" id="password-confirmation" autocomplete="off">
                </div>
            </div>
        </fieldset>
        <div>
            <div class="primary">
                <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
            </div>
        </div>
    </form>
    <script>
        require([
            "jquery",
            "mage/mage"
        ], function($){
            var dataForm = $('#form-validate');
            var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

            dataForm.mage('validation', {
                <?php if ($_dob->isEnabled()): ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    }
                    else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
                <?php else: ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                <?php endif ?>
            });

        });
    </script>
    <script type="text/x-magento-init">
    {
        "#change-password": {
            "setPassword": {
                "currentPasswordId": "#current-password",
                "passwordId": "#password",
                "confirmationId": "#password-confirmation",
                "passwordContainer": "fieldset.fieldset.password",
                "showOnDefault": <?php /* @escapeNotVerified */ echo $block->getChangePassword() ? 'true' : 'false' ?>
            }
        }
    }
</script>
</div>

