<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="col-sm-9 col-xs-9 account-area-container">
    <?php echo $block->getChildHtml('form_before')?>
    <form class="form form-newsletter-manage" action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="block-title"><span><?php /* @escapeNotVerified */ echo __('Subscription option') ?></span></div><br>
            <div>
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php /* @escapeNotVerified */ echo __('General Subscription') ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="subscription" class="label"><span><?php /* @escapeNotVerified */ echo __('General Subscription') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary"><button type="submit" title="<?php /* @escapeNotVerified */ echo __('Save') ?>" class="action save primary"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button></div>
            <div class="secondary"><a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a></div>
        </div>
    </form>
    <?php /* Extensions placeholder */ ?>
    <?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
</div>

