<h2>Contact Details</h2>
<?php
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
//
//print_r($storeManager->getStore()->getEmail());
//?>
<ul>
    <li class="contact-page-telephone"> +44 (0)20 7377 1801</li>
    <li class="contact-page-email">customerservices@weadmire.net</li>
    <li class="contact-page-address">
        WeAdmire Ltd
        <br/>
        13-15 Great Eastern Street
        <br/>
        London,
        <br/>
        EC2A 3EJ
    </li>
    <li class="contact-page-social">
        <a href="#"><img src="<?php echo $this->getViewFileUrl('Magento_Contact::images/contact-page-ico-twitter.png') ?>" alt=""/></a>
        <a href="#"><img src="<?php echo $this->getViewFileUrl('Magento_Contact::images/contact-page-ico-gplus.png') ?>" alt=""/></a>
        <a href="#"><img src="<?php echo $this->getViewFileUrl('Magento_Contact::images/contact-page-ico-instagram.png') ?>" alt=""/></a>
        <a href="#"><img src="<?php echo $this->getViewFileUrl('Magento_Contact::images/contact-page-ico-facebook.png') ?>" alt=""/></a>
    </li>
</ul>