<?php
/**
 * Created by PhpStorm.
 * User: Chamal
 * Date: 3/10/16
 * Time: 9:55 AM
 */

/**
 * @var $block \Muaw\Related\Block\Related
 */

$_quote = $block->getQuote();
$items = $_quote->getAllVisibleItems();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$_media_path = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

foreach ($items as $item) {
    $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
    $artworker = $_product->getAdmireSticker();
    //echo $_media_path.'catalog/product'.$artworker. '<br>';
} ?>

