<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <span class="option-visuals">
        <span class="product-selection-gender"></span>
        <span class="product-selection-color"></span>
        <span class="product-selection-size"></span>
    </span>
    <button type="submit"
            title="<?php /* @escapeNotVerified */
            echo $buttonTitle ?>"
            class="action tocart"
            id="product-addtocart-button">
        <span>
            <?php /* @escapeNotVerified */
            echo $buttonTitle ?>
        </span>

    </button>
    <?php echo $block->getChildHtml('', true) ?>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));
                    return false;
                }
            });
        });
    </script>
<?php endif; ?>