    <?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div data-block="minicart" class="header-cart pull-right minicart-wrapper">
    <a class="showcart" href="<?php /* @escapeNotVerified */
    echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
        <img src="<?php echo $this->getViewFileUrl('Magento_Checkout::images/header-ico-cart.png') ?>"
             alt="<?php echo __('cart icon') ?>"/>
        <span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --> ITEM(S)</span>
        <span class="header-cart-total-price">
             <span data-bind="html: cart().subtotal"></span>
        </span>
    </a>

    <div class="fake-mobile-cart">
        <a href="<?php /* @escapeNotVerified */
        echo $block->getShoppingCartUrl(); ?>"
           data-bind="scope: 'minicart_content'">
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
        <img class="pull-right" src="<?php echo $this->getViewFileUrl('Ashsmith_HelloWorld::images/mobile-header-cart.png') ?>" alt=""/>
        <div class="mobile-cart-items"><span class="counter-number"><!-- ko text: cart().summary_count --><!-- /ko --> ITEM(S)</span></div>
        <div class="mobile-cart-price"><span data-bind="html: cart().subtotal"></span></div>
        </a>
    </div>


    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
        echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */
        echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }


    </script>
</div>

